# Team project 1: Linear Regression, Support Vector Regression (SVR), Decision Tree Regression and Random Forest Regression
### Authors: Carmen Gasco and Jackson Gawarecki
Version: 1.20.3, 
Spring semester

In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
dataset=pd.read_csv('dataset.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gender               224 non-null    int64
 1   Age Range            224 non-null    int64
 2   Head Size(cm^3)      224 non-null    int64
 3   Brain Weight(grams)  224 non-null    int64
dtypes: int64(4)
memory usage: 7.1 KB


In [4]:
dataset.head()

Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0       1          1             4512                 1530
1       1          1             3738                 1297
2       1          1             4261                 1335
3       1          1             4177                 1590
4       1          1             3585                 1300

In [5]:
dataset.isnull().sum()

Gender                 0
Age Range              0
Head Size(cm^3)        0
Brain Weight(grams)    0
dtype: int64

# Multiple Linear Regressor

In [6]:
X=dataset[['Gender', 'Age Range', 'Head Size(cm^3)']]
y=dataset[['Brain Weight(grams)']]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=42)

In [8]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [9]:
y_pred=regressor.predict(X_test)

## Predictions

In [10]:
#Case1
regressor.predict([[1,1,3777]])

array([[1343.87313736]])

In [11]:
#Case2
regressor.predict([[1,1,4424]])

array([[1509.36609384]])

In [12]:
#Case3
regressor.predict([[1,1,4036]])

array([[1410.12147697]])

In [13]:
#Case4
regressor.predict([[1,1,4315]])

array([[1481.48551848]])

In [14]:
#Case5
regressor.predict([[1,1,4270]])

array([[1469.97518921]])

In [15]:
#Case6
regressor.predict([[1,2,3727]])

array([[1310.80190525]])

In [16]:
#Case7
regressor.predict([[1,2,3666]])

array([[1295.19901446]])

In [17]:
#Case8
regressor.predict([[2,2,3394]])

array([[1203.41021731]])

In [18]:
#Case9
regressor.predict([[2,2,3692]])

array([[1279.63417563]])

In [19]:
#Case10
regressor.predict([[2,2,3389]])

array([[1202.13129184]])

In [20]:
#Case11
regressor.predict([[2,2,4204]])

array([[1410.59614429]])

In [21]:
#Case12
regressor.predict([[2,2,3214]])

array([[1157.36890021]])

In [22]:
from sklearn.metrics import r2_score
print('R-Square', r2_score(y_test,y_pred))

R-Square 0.5186242086390903


In [23]:
from sklearn.metrics import mean_squared_error as mse
from math import sqrt
rms=sqrt(mse(y_test,y_pred))
print('The root mean squared error is',rms)

The root mean squared error is 66.94213669838602


# SVR

In [24]:
X=dataset[['Gender', 'Age Range', 'Head Size(cm^3)']]
y=dataset[['Brain Weight(grams)']]

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=42)

In [26]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
sc_y=StandardScaler()
X_train=sc_X.fit_transform(X_train)
y_train=sc_y.fit_transform(y_train)

In [27]:
from sklearn.svm import SVR
regressor=SVR(kernel='rbf')
regressor.fit(X_train, y_train)   

/Users/carmengascogalvez/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

In [28]:
y_pred=sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)).reshape(-1,1))

### Validation

In [29]:
#Case1
sc_y.inverse_transform(regressor.predict(sc_X.transform([[1,1,3777]])).reshape(-1,1))

array([[1330.13843789]])

In [30]:
#Case2
sc_y.inverse_transform(regressor.predict(sc_X.transform([[1,1,4424]])).reshape(-1,1))

array([[1503.45891121]])

In [31]:
#Case3
sc_y.inverse_transform(regressor.predict(sc_X.transform([[1,1,4036]])).reshape(-1,1))

array([[1394.54125949]])

In [32]:
#Case4
sc_y.inverse_transform(regressor.predict(sc_X.transform([[1,1,4315]])).reshape(-1,1))

array([[1477.23459502]])

In [33]:
#Case5
sc_y.inverse_transform(regressor.predict(sc_X.transform([[1,1,4270]])).reshape(-1,1))

array([[1464.54577335]])

In [34]:
#Case6
sc_y.inverse_transform(regressor.predict(sc_X.transform([[1,2,3727]])).reshape(-1,1))

array([[1310.42153843]])

In [35]:
#Case7
sc_y.inverse_transform(regressor.predict(sc_X.transform([[1,2,3666]])).reshape(-1,1))

array([[1293.83054452]])

In [36]:
#Case8
sc_y.inverse_transform(regressor.predict(sc_X.transform([[2,2,3394]])).reshape(-1,1))

array([[1208.06177103]])

In [37]:
#Case9
sc_y.inverse_transform(regressor.predict(sc_X.transform([[2,2,3692]])).reshape(-1,1))

array([[1317.27315037]])

In [38]:
#Case10
sc_y.inverse_transform(regressor.predict(sc_X.transform([[2,2,3389]])).reshape(-1,1))

array([[1206.00063275]])

In [39]:
#Case11
sc_y.inverse_transform(regressor.predict(sc_X.transform([[2,2,4204]])).reshape(-1,1))

array([[1345.18594696]])

In [40]:
#Case12
sc_y.inverse_transform(regressor.predict(sc_X.transform([[2,2,3214]])).reshape(-1,1))

array([[1138.98263048]])

In [41]:
from sklearn.metrics import r2_score
print('R-Square', r2_score(y_test,y_pred))

R-Square 0.5014536540493876


In [42]:
from sklearn.metrics import mean_squared_error as mse
from math import sqrt
rms=sqrt(mse(y_test,y_pred))
print('The root mean squared error is',rms)

The root mean squared error is 68.12558054984444
