# Jackson Gawarecki and Carmen Gascó Gálvez
## Team Project 1
### DS-160-02 Intro To Data Science
#### Spring 2022

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
dataset=pd.read_csv("dataset.csv")

In [3]:
dataset.head()

Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0       1          1             4512                 1530
1       1          1             3738                 1297
2       1          1             4261                 1335
3       1          1             4177                 1590
4       1          1             3585                 1300

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gender               224 non-null    int64
 1   Age Range            224 non-null    int64
 2   Head Size(cm^3)      224 non-null    int64
 3   Brain Weight(grams)  224 non-null    int64
dtypes: int64(4)
memory usage: 7.1 KB


# Missing values

In [5]:
dataset.isnull().sum()

Gender                 0
Age Range              0
Head Size(cm^3)        0
Brain Weight(grams)    0
dtype: int64

# Create Different Copies of your Data

In [6]:
data_LR=dataset
data_SVR=dataset
data_DT=dataset
data_RF=dataset

# Decision Tree Regresson

In [83]:
X=data_DT[['Gender','Age Range','Head Size(cm^3)']]
y=data_DT[['Brain Weight(grams)']]

In [84]:
#X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2, random_state=0)
#X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.15, random_state=0)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.1, random_state=0)

In [85]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import plot_tree

In [86]:
regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(X_train,y_train)

DecisionTreeRegressor(random_state=0)

In [87]:
y_pred=regressor.predict(X_test)

### Predict

In [88]:
regressor.predict([[1,1,777]])

array([955.])

In [89]:
regressor.predict([[1,1,4424]])

array([1505.])

In [90]:
regressor.predict([[1,1,4036]])

array([1422.])

In [91]:
regressor.predict([[1,1,4315]])

array([1506.])

In [92]:
regressor.predict([[1,1,4270]])

array([1335.])

In [93]:
regressor.predict([[1,2,3727]])

array([1290.])

In [94]:
regressor.predict([[1,2,3666]])

array([1222.])

In [95]:
regressor.predict([[2,2,3394]])

array([1215.])

In [96]:
regressor.predict([[2,2,3692]])

array([1305.])

In [97]:
regressor.predict([[2,2,3389]])

array([1120.])

In [98]:
regressor.predict([[2,2,4204]])

array([1256.])

In [99]:
regressor.predict([[2,2,3214]])

array([1110.])

### R-Square and MSE

In [100]:
from sklearn.metrics import r2_score
print("R-Square",r2_score(y_test,y_pred))

R-Square 0.34807378217160145


In [101]:
from sklearn.metrics import mean_squared_error as msc
from math import sqrt
rms=sqrt(msc(y_test,y_pred))
print('The mean squared error is',rms)

The mean squared error is 79.18497881268402


# Random Forest Regression

In [102]:
X=data_RF[['Gender','Age Range','Head Size(cm^3)']]
y=data_RF[['Brain Weight(grams)']]

In [103]:
#X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2, random_state=0)
#X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.15, random_state=0)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.1, random_state=0)

In [104]:
from sklearn.ensemble import RandomForestRegressor

In [105]:
regressor=RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_train,y_train)

<ipython-input-105-3a5204d5c8ac>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train,y_train)


RandomForestRegressor(n_estimators=20, random_state=0)

In [106]:
y_pred=regressor.predict(X_test)

## Predict

In [107]:
regressor.predict([[1,1,777]])

array([993.6])

In [108]:
regressor.predict([[1,1,4424]])

array([1510.88333333])

In [109]:
regressor.predict([[1,1,4036]])

array([1407.55])

In [110]:
regressor.predict([[1,1,4315]])

array([1475.8])

In [111]:
regressor.predict([[1,1,4270]])

array([1390.3])

In [112]:
regressor.predict([[1,2,3727]])

array([1295.1])

In [113]:
regressor.predict([[1,2,3666]])

array([1225.6])

In [114]:
regressor.predict([[2,2,3394]])

array([1196.75])

In [115]:
regressor.predict([[2,2,3692]])

array([1319.25])

In [116]:
regressor.predict([[2,2,3389]])

array([1123.25])

In [117]:
regressor.predict([[2,2,4204]])

array([1374.6])

In [118]:
regressor.predict([[2,2,3214]])

array([1116.35])

## R-squared and MSE

In [119]:
print("R-Square",r2_score(y_test,y_pred))

R-Square 0.49302515747992803


In [120]:
rms=sqrt(msc(y_test,y_pred))
print('The mean squared error is',rms)

The mean squared error is 69.82915486790039
